language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
# aun no hay req tests jeje
#  - pip install -r requirements-test.txt
  - python manage.py migrate
# command to run tests
script: python manage.py test